### ISSUE TITLE
你好，我想请教一个问题

### ISSUE THREAD

**Issue by wzfxue** [songjiahong/revitapisamples#2]
墙体开洞使用洞口工具只能矩形。
现在我想开一个任意形状的洞口，而不是用编辑轮廓的方式。
2018版本如下操作：
构件--内置构件--常规模型--洞口--画出想要的形状点完成模型，墙体就会开一个洞口。
问题：我想通过代码的方式实现，应该是怎么个思路呢？
InstanceVoidCutUtils使用这个好像不太对。

**Comment by songjiahong** [comment]
Check NewOpening in Autodesk.Revit.Creation.Document

**Comment by wzfxue** [comment]
我想要的是任意形状的洞口，NewOpening对墙只能开矩形。有什么好的办法吗？   @songjiahong

**Comment by songjiahong** [comment]
NewOpening的参数有CurveArray，理论上应该封闭的图形都可以，你可以尝试一下

**Comment by wzfxue** [comment]
对墙体Wall的参数只能是两个坐标点

**Comment by songjiahong** [comment]
NewOpening(Element, CurveArray, Boolean)的第一个参数也可以是墙

**Comment by wzfxue** [comment]
老大，这个真的不能！不信你试试，墙体只支持矩形
